### ISSUE TITLE
Decrypt with URL parameter? 

### ISSUE THREAD

**Issue by noamross** [derhuerst/self-decrypting-html-page#2]
Would it be possible to create a version of this where the page decrypts itself if the key is provided as a URL parameter or anchor?

**Comment by derhuerst** [comment]
I appreciate the the effort to make using this tool more seamless, but how would that work without sacrificing the concept of this tool? Because `self-decrypting-html-page` generates a *self-contained*/standalone HTML file, the idea is that you can (and should) treat it like any other local file (e.g. a Word document).

- Hosting the generated file via a web server would make add more possibilities (thus, incentives) to actually serve someone an HTML page that sniffs the password. With a strictly [out-of-band](https://en.wikipedia.org/wiki/Out-of-band) transfer of the file (assuming the sender is trustworthy and the transmission is safe against manipulation by third parties), the receiver can store the file and open it at any time later.
- Although *I think* it is possible to pass a [query parameter](https://en.wikipedia.org/wiki/URL#Syntax) or anchor/fragmet to a `file://` URL, how really does that in which scenario? I assume more technical people would use other tools like PGP/GPG, OpenSSL, [private-pipe](https://github.com/emilbayes/private-pipe).

**Comment by noamross** [comment]
Indeed the application I was thinking of was definitely the context of serving on a web server, in the context where one only had the ability to serve static files. I realize the biggest issue is that, even if one has HTTPS, the _url_ can be intercepted.

**Comment by derhuerst** [comment]
> […] even if one has HTTPS, the _url_ can be intercepted.

The [URL's anchor/fragmet](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#basics_anatomy_of_a_url) is not sent to the server.

But still, I'm very hesitant to introduce the incentive to break this tool's security by hosting the decryption page.
